name: "Add version tak"
description: "Creates tag"
author: "Pawel Nalepka"
inputs:
  github_token:
    description: "GITHUB_TOKEN. Optional if you use checkout@v2 action."
    required: false
  file:
    description: "file with version"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "tag"
  color: "blue"
